### PR TITLE
Remove the last comma when show the genre list of book detail

### PR DESCRIPTION
**Pull request by xiangaoole**
截屏2020-10-07 上午11 57 39

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@hamishwillee

**Comment by hamishwillee** [comment]
Thanks very much @xiangaoole . I'll look at this in the coming week.

**Comment by hamishwillee** [comment]
Thanks very much. Looks great. Merged.

**Comment by hamishwillee** [comment]
PS FYI Docs already match this: https://wiki.developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_detail_page

**Pull request merged**
