### PR TITLE
Update bookController.index #76

### PR DESCRIPTION
**Pull request by ElliottLMz**
Replaced with MongooseModel.countDocuments

#76

### CODE REVIEW

**Comment by ElliottLMz** [comment]
Quick question, would this automatically update the documentation on MDN or would that need to be manually updated to make the correction?
_(Unsure if MDN shows count or countDocuments)_

**Comment by hamishwillee** [comment]
Hi @ElliottLMz ,

Thanks very much for this. Really appreciated!

Sadly nothing magically updates. Probably have to be fixed in the sub documents of https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data

How did you test this? Specifically, I use this project to test issues people come up with in the docs. I start by installing [package.json](https://github.com/mdn/express-locallibrary-tutorial/blob/master/package.json) dependencies.  So the fix needs to work with those dependencies or the dependencies need to be updated to match and we quickly retest that nothing else falls over.

Does that make sense?

**Comment by Spikatrix** [comment]
Just tested and @ElliottLMz is right. I cloned and ran this repo and got the deprecation warnings. When I changed `count(callback)` to `countDocuments(callback)`, the warnings went away and everything still works.

However, https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Home_page uses `countDocuments({}, callback)` rather than `countDocuments(callback)` as in this PR. Both of these seems to work just fine without any warnings

**Comment by hamishwillee** [comment]
Thanks @Spikatrix , Arrggg. So either we merge this and update the MDN docs, or we update this PR to use `countDocuments({}, callback)` instead?

**Comment by Spikatrix** [comment]
I think it would be better to merge this and update the MDN docs as specifying `{}` seems to be redundant.

**Comment by hamishwillee** [comment]
Hmmm, looking closer I don't think I agree. The MDN format of the call allows you to match documents, which we don't do in this case, but as a learning experience you want people to know about. I'm also not sure how javascript is matching the parameters in the case here.

So I'm going to propose this is updated to match MDN. 

@Spikatrix @ElliottLMz  is that something one of you could do and test? If not, will go on my big list.

**Comment by hamishwillee** [comment]
Closing - the changes integrated in PR #102.

Thanks very much @ElliottLMz @Spikatrix - this was really useful when it came time to do this. But I couldn't resolve the conflicts and wanted to update the syntax to match the docs.

**Pull request closed without merging**
