### PR TITLE
fix bookinstance_form.pug 

### PR DESCRIPTION
**Pull request by AndreyKozhevnikov**
1. the status of a bookInstance is wrong when this bookInstance is updated
2. the book of a bookInstance is wrong when this bookInstance is updated

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
@hamishwillee do you have any opinion on this? It looks pretty reasonable to me.

**Comment by hamishwillee** [comment]
Yes it looks right to me - thanks @AndreyKozhevnikov. Obviously not enough time spent testing the update case.
BUT I have not built and tested this.

**Comment by hamishwillee** [comment]
OK, just verified the defect. Will verify the fix now.

**Comment by chrisdavidmills** [comment]
I tested it, and it works fine.

**Comment by hamishwillee** [comment]
Awesome. Thanks. Me too: https://hidden-ridge-60400.herokuapp.com/catalog :-)

**Pull request merged**
