### PR TITLE
Update express-validator package to v7.0.1 and replace deprecated code with recommended code

### PR DESCRIPTION
**Pull request by TruePadawan**
### Description
I updated the express-validator package to v7.0.1 and also updated deprecated code from the package to the recommended code

### Additional details
I've tested that the app works fine after the changes

### CODE REVIEW

**Comment by schalkneethling** [comment]
Hey, @TruePadawan 👋 Thank you for your pull request. We manage dependency updates using Dependabot. You can see a [pull request here](https://github.com/mdn/express-locallibrary-tutorial/pull/179) proposing the same package update. If you can revert the change to `package.json` and `package-lock.json`, we can continue the review of the pull request.

**Comment by TruePadawan** [comment]
@schalkneethling I'm new to contributing to repos so not sure exactly the proper procedures but I think I've just done that, I reverted the commit where I updated the package

**Comment by schalkneethling** [comment]
> @schalkneethling I'm new to contributing to repos so not sure exactly the proper procedures but I think I've just done that, I reverted the commit where I updated the package

Great stuff! That worked perfectly.

**Comment by TruePadawan** [comment]
What next?

**Review by schalkneethling — APPROVED** [review]
Looks good! Thanks, @TruePadawan - For reference: https://express-validator.github.io/docs/api/validation-chain/#optional

**Comment by TruePadawan** [comment]
@hamishwillee What new changes? The PR already has the relevant commits, I'm not sure what you mean.

**Comment by hamishwillee** [comment]
Perhaps I'm blind, but here I see changes in several files, but in the content PR I only see the author changes (not the bookinstance changes). This shows a check on the "old" check across the express docs.

image

**Comment by TruePadawan** [comment]
Ah alright, I think I've done it now, probably.

**Comment by hamishwillee** [comment]
Yes, great job. Thanks very much.

**Pull request merged**
