### PR TITLE
Removed deprecated requires for express-validator

### LINKED ISSUE #81: Deprecation warnings for express-validator
I'm getting deprecation warnings for `express-validator/filter` and `express-validator/check`:

```
$ DEBUG=express-locallibrary-tutorial:* npm run devstart         

> express-locallibrary-tutorial@0.0.0 devstart /home/user/Documents/Code/express-locallibrary-tutorial
> nodemon ./bin/www

[nodemon] 1.19.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./bin/www`
express-validator: requires to express-validator/check are deprecated.You should just use require("express-validator") instead.
express-validator: requires to express-validator/filter are deprecated.You should just use require("express-validator") instead.
  express-locallibrary-tutorial:server Listening on port 3000 +0ms

```

### PR DESCRIPTION
**Pull request by Spikatrix**
Removed deprecated requires for express-validator

Fixes #81

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks very much - looks good.
1. Did you test this?
2. Does it still work with the current package.json
3. Once merged, can you do corresponding changes in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Tutorial_local_library_website ?

**Comment by Spikatrix** [comment]
> 1. Did you test this?

Yes, it works fine for express-validator v6.0.0 and newer versions.

> 2. Does it still work with the current package.json

Just tested, and no, it does not. The current `package.json` uses express-validator v5.3.1 where  `check` and `filter` aren't deprecated. As seen [here](https://github.com/express-validator/express-validator/releases/tag/v6.0.0), it has been deprecated from v6.0.0 onwards.

> 3. Once merged, can you do corresponding changes in https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Tutorial_local_library_website ?

Sure, I'll try after when it's merged

<hr>

Should I close this PR (and issue) since `package.json` here is using express-validator v5.3.1 or should I update it to the latest version as of now?

**Comment by hamishwillee** [comment]
Thanks @Spikatrix 

> Just tested, and no, it does not. The current package.json uses express-validator v5.3.1 where check and filter aren't deprecated. As seen here, it has been deprecated from v6.0.0 onwards.

The problem I have is that the package json represents a line in the sand for a well tested environment. Running on any other version is not verified.

Now your fix looks great, and I want to accept it, but to do so we need to make sure that all changes appropriate for v6 work (and then we save that as the current version for package.json). 

So also we would need to check whether these changes have impact

> #616, #722 - Validators and sanitizers will now run in the order they are specified, instead of always running sanitizers first, then validators;

Should order change for declaration or is this still good.

> #592, #641, #632, #630, #580, #651, #711 - non-string values will now be sanitized;

Is there an opportunity missed here in right way to do sanitisation?

**Comment by Spikatrix** [comment]
Thanks for the reply.

You're right that there's a fair bit of changes in the newer versions of express-validator. Related: #69 

I'll tinker around with the sanitizers and validators and check if everything still works as expected

**Comment by hamishwillee** [comment]
Thanks very much. I try update to latest version of everything every year or so, but keeping it up to date as it goes is better. Can only happen with the kind support of others like you, as I've somewhat moved on.

**Comment by hamishwillee** [comment]
Closing this now. Thank you very much for the post - I fixed it in a slightly different PR along with some related fixes and associated changes to the docs.

**Pull request closed without merging**
