### PR TITLE
Add alphabetical sorting

### PR DESCRIPTION
**Pull request by jnsjknn**
Alphabetical sorting for:
- Author list dropdown when creating a new book
- Book list when viewing all books
- Book list dropdown when creating a new book instance

### CODE REVIEW

**Comment by chrisdavidmills** [comment]
Thanks for your submission. This sounds useful, but I'll wait for @hamishwillee to comment here.

**Comment by hamishwillee** [comment]
@jnsjknn Thanks. I'm in 2 minds on this. On one hand sorting is something people might want to do, on the other it teaches nothing particular new to people wanting to learn the express framework  - essentially they already know how to call functions in a pug template. So typically I don't show this because I want the code as simple as possible. 

@chrisdavidmills Thoughts? I have not tested this code but it looks OK.

**Comment by jnsjknn** [comment]
Good point. I didn't think about the tutorial aspect of this. 

I just finished the tutorial myself and realized a longer list of books would be awkward to browse through if there's no sorting.

**Comment by hamishwillee** [comment]
> realized a longer list of books would be awkward to browse through if there's no sorting.

Definitely a good point, and in a real library I'd agree.

Let's see what @chrisdavidmills  says. If he is OK with it, are you OK to update the corresponding docs on MDN?

**Comment by jnsjknn** [comment]
Sure, but I'm new to things like this. Where can I edit it? Should I only edit the code parts of the guide or also write an explanation for them?

**Comment by chrisdavidmills** [comment]
OK, let's get this merged then.

@jnsjknn Editing the code parts of the tutorial would be nice. A sentence explaining what the new line does would be good as well.

I'm happy to assist you in doing the edit. The best way is to try it, and then let me know you've done it so I can review your work.

**Comment by jnsjknn** [comment]
@chrisdavidmills I added the code parts into the tutorial. The explanations should be checked as I neither am a native English speaker nor have a good understanding of the proper coding terms/vocabulary. I edited the following pages:

- [Book List Page](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Book_list_page)
- [Create BookInstance Form](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_BookInstance_form)
- [Create Book Form](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/forms/Create_book_form)

All changes were made under the "View" subheading.

**Comment by chrisdavidmills** [comment]
@jnsjknn 

Thanks so much for your help on this! Your additions look mostly fine, and I've just made a couple  of small copy edits.

I did have one question — are the code lines you added supposed to have `- ` at the start of them? I don't know this type of code very well, but it looked strange ;-)

**Comment by hamishwillee** [comment]
Thanks @jnsjknn for this - and to @chrisdavidmills for following up. I'm a bit under the pump right now.

**Comment by jnsjknn** [comment]
@chrisdavidmills Pug syntax is a bit strange but yes, the code is supposed to have the - in front of them. That's how pug knows we're using JavaScript.

**Comment by chrisdavidmills** [comment]
@jnsjknn ok, sounds fine then. Thanks for your help!

**Pull request merged**
