### PR TITLE
Escape warning: "current Server Discovery and Monitoring engine is deprecated..."

### PR DESCRIPTION
**Pull request by idawnwon**
`useUnifiedTopology: true` can escape the warning: 
```
(node:79) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
```

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks, looks great. 
The problem I have with this is that the example is based against a particular package.json. Are your dependencies the same as that package.json or newer. If newer, we need to know what they are and update package.json too. Also understand that all tests have been run.

**Comment by idawnwon** [comment]
@hamishwillee, great to hear from you! I am a big fan of the tutorial you shared!

Well, according to my practice, as I followed the tutorial and used this repo, the `package.json` is just fine (except the Pug's version is a bit old, caused npm warns. Npm suggests pug 3.0.0.). I didn't use any other  `package.json`.

According to [Mongoose latest official doc](https://mongoosejs.com/), `useUnifiedTopology: true` is included:
```javascript
const mongoose = require('mongoose');
mongoose.connect('mongodb://localhost:27017/test', {useNewUrlParser: true, useUnifiedTopology: true});
```

**Comment by hamishwillee** [comment]
Thanks very much for this. I'm really glad you like it. I'm planning on updating this tutorial within the next month or so. I will do some final checks and merge this then if it is OK with you. 

FYI @chrisdavidmills

**Comment by idawnwon** [comment]
Super! Keep in touch!

**Comment by hamishwillee** [comment]
Finally got to this. Fixed it up as part of https://github.com/mdn/express-locallibrary-tutorial/pull/97 
Thanks very much!

**Pull request closed without merging**
