### PR TITLE
Refactored style.css and updated margin for block content; replaced var with const for improved code quality.

### PR DESCRIPTION
**Pull request by Zack-Dx**
### Description
Refactored style.css and updated margin for block content; replaced var with const for improved code quality.

Improved code quality by updating block content margin in style.css and refactoring code to use const instead of var.

### Motivation

The changes made aim to improve the code quality and enhance the website's visual appearance. Updating the margin for block content in style.css provides better readability, while switching from var to const promotes a more secure and maintainable codebase. By continuously refining the code, we can ensure better performance, stability, and scalability for the website.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thank you @Zack-Dx 

I'd rather not take these changes because they don't add anything much to the learning experience for people following the tutorial. Yes the changes to the styles are prettier/better, but you'll note I don't go into any real detail on styling in the tutorial because it isn't part of the core focus. If I was to take this, I'd also have to update the corresponding docs on MDN.

The changes to `bin/www` changes were left because this is auto-generated code. I've been hoping the express generator would be updated so I could update it. I would take this change if it wasn't mixed with the style changes.

Hope that makes sense?

**Comment by Zack-Dx** [comment]
> Thank you @Zack-Dx 
> 
> 
> 
> I'd rather not take these changes because they don't add anything much to the learning experience for people following the tutorial. Yes the changes to the styles are prettier/better, but you'll note I don't go into any real detail on styling in the tutorial because it isn't part of the core focus. If I was to take this, I'd also have to update the corresponding docs on MDN.
> 
> 
> 
> The changes to `bin/www` changes were left because this is auto-generated code. I've been hoping the express generator would be updated so I could update it. I would take this change if it wasn't mixed with the style changes.
> 
> 
> 
> Hope that makes sense? 

Alright np!

**Comment by hamishwillee** [comment]
Thanks - also for taking the time to do fixes and not just ignore problems you see as you're going along. Much appreciated.

**Comment by Zack-Dx** [comment]
> Thanks - also for taking the time to do fixes and not just ignore problems you see as you're going along. Much appreciated.

Express Generator won't likely update it any longer, in my opinion. Anyhow, if you could point me in the direction of a repository, a decent tutorial, or a document that explains how to create a rest API using Express using proper auth while logging activities to provide code that is ready for production and has appropriate error handling, that would be greatly appreciated. If so, it would be greatly appreciated if you could provide me some advice on this as well.

**Comment by hamishwillee** [comment]
I can't sorry - if I knew enough about auth to write about it, I would have added a tutorial on that too.

**Comment by Zack-Dx** [comment]
> I can't sorry - if I knew enough about auth to write about it, I would have added a tutorial on that too.

you can have a look at this https://github.com/Zack-Dx/JWT_AUTH_COMPLETE

**Comment by hamishwillee** [comment]
Thanks. At some point. I'm hoping someone else will volunteer to extend the tutorial in a "compatible" way.

**Pull request closed without merging**
