### PR TITLE
Fix author name

### PR DESCRIPTION
**Pull request by Benneee**
This is the PR for issue #80  

- Populated the DB with the command 'node populatedb <mongodb-url>'

- Checked for the existence of the names, family_name and first_name, before returning the virtual for name.

- Added a script to start the project; this alleviated the need to always type `DEBUG=local-library:* nodemon ./bin/www` in the terminal.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Thanks very much. I haven't run this but it looks very sane :-)

Passes basic sanity tests right?

**Comment by Benneee** [comment]
Yes,  it passes sanity test. All the pages render accordingly and the data is very much the same as expected.

**Comment by hamishwillee** [comment]
Thank you! Merged. I'll leave you the fun of updating the docs as well :-)

**Comment by Benneee** [comment]
LOL! Thank you very much, I'm very grateful. You have just made my day.

By "updating the docs", do you mean updating the tutorial? If that is it or not, kindly direct me to how I will get started on it

**Comment by hamishwillee** [comment]
Yes, I mean updating the tutorial on MDN wiki. IN particular there are probably bits where this code gets copy-pasted as written down.

Also the new addition where you *alleviated the need to always type DEBUG=local-library:* nodemon ./bin/www in the terminal.* might be explained :-)

**Comment by Benneee** [comment]
Alright then, I'll jump right on it.

Thank you.

**Comment by Benneee** [comment]
I have updated the wiki in the appropriate places. If I missed anything or did a little too much, kindly tell me. See the links to my changes below:

1. For package.json script addition
- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/skeleton_website#Enable_server_restart_on_file_changes

2. For checks for  name virtual returned to the view
- https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose#Defining_the_LocalLibrary_Schema

Thanks once again.

**Comment by hamishwillee** [comment]
I think this is about the right level - I did a minor update to the first text for my own style. Thanks very much.

@chrisdavidmills FYI, please meet Benedict (@Benneee) who has made some useful changes to the Express tutorial. Benedict, Chris runs this area of the MDN.

**Comment by Benneee** [comment]
I'm grateful I could help. Thank you for your time as well.

**Comment by chrisdavidmills** [comment]
Super; thanks for all your work @Benneee !

**Comment by jsingh-github** [comment]
The Code on MDN is not up to date. I had the same issue when following the code in the link below. 
https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/mongoose

I cloned the project from github and the book list rendered the author name. Appreciate if the MSN content can be updated please.

**Pull request merged**
