### PR TITLE
Auth branch

### PR DESCRIPTION
**Pull request by caglarturali**
Hi folks. I've implemented user authentication and -quite trivial- authorization functionality for our awesome locallibrary project :) At first, I was thinking about documenting it but honestly, it's not gonna happen any time soon. So, I decided to create a new branch for it. I think it would be nice to have such a functionality even though we've not documented it yet. You can check out the live version of auth branch [here](https://awesomelibrary.herokuapp.com/). And if you want to document it, go for it, you're more than welcome.

By the way, I just noticed that this branch will end up merged into the master branch if you approve it. And that would be controversial. So, I can change base branch of pull request if you create a new branch preferably named `auth`.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Ignore my comment in https://github.com/mdn/express-locallibrary-tutorial/pull/55 :-)

Thanks very much for this - always great to get new features and improvements.

Can you push this to _this_ repo? Ie if this is upstream repo do `git push upstream auth` (it may be you are saying you don't have the rights?  

I plan to look at this tutorial again in the next couple of months and when I do that I will take the time to decide whether/how we should merge the content and add documentation. It might be we do just as you have - create a link from readme.

**Comment by caglarturali** [comment]
Nope, I can't push to this repo. It responds with permission denied message.

**Comment by hamishwillee** [comment]
Thanks. OK, I have created the branch.

**Comment by caglarturali** [comment]
Ok, I've changed base branch from `master` to `auth`. It should be good to go now.

**Comment by hamishwillee** [comment]
Thanks!

**Pull request merged**
