### PR TITLE
multi genre sanitization code updated to express validator v4

### PR DESCRIPTION
**Pull request by VaibhavAjayGupta**
First converted genre to an array and then used wildcard for sanitization.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Awesome thanks. You're way ahead of me! I'll have to read up on this on the weekend.

One last task then, removing the validator from app.js, as there are no other instances of the older API and we hence no longer need it!

**Comment by VaibhavAjayGupta** [comment]
Great.

**Comment by hamishwillee** [comment]
Thanks very much for this. Works a treat. I'm glad you did this, because I don't think much of the validator documentation in this area. I'll update the docs shortly.

**Comment by VaibhavAjayGupta** [comment]
Thank you.

**Pull request merged**
